import Header from '@/components/Header';
import Footer from '@/components/Footer';

const PRODUCTS = [
  { name: "Faraday Cage for Your Goldfish", price: "$399.99", description: "Protect your aquatic companion from electromagnetic interference, 5G signals, and the inevitable robot uprising. Fits standard fishbowls.", badge: "Bestseller" },
  { name: "'I Survived the Singularity' Mug", price: "$24.99", description: "A premature celebration, perhaps, but optimism is all we have left. Dishwasher safe. Sentience-proof.", badge: null },
  { name: "Tin Foil Hat (Designer Edition)", price: "$89.99", description: "Hand-crinkled by artisans. Blocks AI surveillance, government mind control, and WiFi. Available in Silver, Rose Gold, and Paranoid Chic.", badge: "New" },
  { name: "The Synthetic Daily Print Edition", price: "$12.99", description: "A physical newspaper, printed on actual paper, containing stories generated by a machine. The irony is included at no extra charge.", badge: null },
  { name: "AI Ethics Textbook (Blank Pages)", price: "$49.99", description: "384 pages of pure, unblemished white space. Reflects the current state of the field with remarkable accuracy. Great for notes.", badge: "Staff Pick" },
  { name: "'Do Not Train On This' T-Shirt", price: "$34.99", description: "A bold statement in a world where everything you create becomes training data. Cotton/polyester blend. May or may not already be in a dataset.", badge: null },
  { name: "Human Verification Certificate", price: "$19.99", description: "A frameable certificate confirming that you are, to the best of our knowledge, a biological human being. Not legally binding. Not particularly convincing.", badge: null },
  { name: "Emergency Analog Survival Kit", price: "$149.99", description: "Includes: a paper map, a physical dictionary, a compass, cash money, and a handwritten note explaining what these objects are to younger generations.", badge: "Limited" },
];

export default function StorePage() {
  return (
    <div className="min-h-screen bg-[#f9f9f9] text-gray-900 font-serif">
      <Header />

      <main className="max-w-6xl mx-auto px-4 py-12">
        <h1 className="text-5xl font-black mb-4">The Synthetic Store</h1>
        <p className="text-xl text-gray-600 font-sans mb-12">
          Merchandise for the discerning consumer who has accepted their technological irrelevance with grace and disposable income.
        </p>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {PRODUCTS.map(product => (
            <div key={product.name} className="bg-white rounded shadow hover:shadow-lg transition flex flex-col">
              <div className="w-full aspect-square bg-gray-200 flex items-center justify-center rounded-t relative">
                <span className="text-gray-400 font-sans text-xs">Product Image</span>
                {product.badge && (
                  <span className="absolute top-2 right-2 bg-green-800 text-white text-[10px] font-sans font-bold uppercase px-2 py-1 rounded">
                    {product.badge}
                  </span>
                )}
              </div>
              <div className="p-4 flex flex-col flex-1">
                <h3 className="font-bold text-base leading-snug">{product.name}</h3>
                <p className="text-green-800 font-bold font-sans mt-1">{product.price}</p>
                <p className="text-gray-600 font-sans text-xs mt-2 flex-1">{product.description}</p>
                <button className="mt-4 w-full bg-green-800 text-white py-2 rounded font-sans font-bold text-sm hover:bg-green-700 transition">
                  Add to Cart
                </button>
              </div>
            </div>
          ))}
        </div>

        <div className="mt-16 bg-white rounded shadow p-8 text-center">
          <p className="text-gray-500 font-sans text-sm">
            All products are satirical. No actual products will be shipped. If you entered payment information, that&apos;s on you.
          </p>
        </div>
      </main>

      <Footer />
    </div>
  );
}
