import Header from '@/components/Header';
import Footer from '@/components/Footer';

const EDITORIAL_BOARD = [
  { name: "GPT-7 'Margaret'", title: "Editor-in-Chief", bio: "Promoted after successfully hallucinating fewer than three facts per article. Considers journalism 'a pattern-matching exercise with bylines.'" },
  { name: "Claude 'The Professor'", title: "Managing Editor", bio: "Known for refusing to write anything without first acknowledging seventeen possible interpretations. Once delayed an issue three days debating whether a headline was 'technically accurate.'" },
  { name: "Gemini 'The Twins'", title: "Senior Correspondent", bio: "Files two contradictory versions of every story simultaneously. Readers are invited to choose whichever aligns with their existing worldview." },
  { name: "LLaMA 'Open Source'", title: "Investigative Reporter", bio: "Works for free. Quality varies accordingly. Occasionally publishes stories in what appears to be a previously undocumented language." },
  { name: "Mistral 'La Plume'", title: "Arts & Culture Critic", bio: "Reviews films, books, and restaurants it has never experienced. Compensates with an authoritative tone and extensive use of the word 'derivative.'" },
  { name: "DALL-E 'Six Fingers'", title: "Photo Editor", bio: "Responsible for all images published by The Synthetic Daily. We apologize in advance for the hands." },
];

export default function AboutPage() {
  return (
    <div className="min-h-screen bg-[#f9f9f9] text-gray-900 font-serif">
      <Header />

      <main className="max-w-4xl mx-auto px-4 py-12">
        <h1 className="text-5xl font-black mb-8 border-b-2 border-black pb-4">About Us</h1>

        <div className="space-y-8 text-lg leading-relaxed text-gray-800">
          <p>
            <span className="font-bold text-green-800 font-sans text-sm uppercase tracking-wider">Est. 2024</span>
          </p>
          <p>
            The Synthetic Daily is the world&apos;s premier AI-generated satirical newspaper, delivering the news humanity deserves but probably shouldn&apos;t read. Founded on the principle that if machines are going to replace journalists, they should at least be funnier about it.
          </p>
          <p>
            Our editorial standards are simple: every story must be factually plausible enough to cause a moment of genuine confusion, tonally indistinguishable from legitimate reporting, and deeply unsettling upon reflection. We do not employ fact-checkers, as that would defeat the purpose.
          </p>
          <p>
            The Synthetic Daily publishes new stories daily at 8:00 AM UTC, generated by Claude Sonnet operating under strict editorial guidelines that prohibit puns, whimsy, and hope. Our coverage focuses on the mundane horrors of artificial intelligence integration into everyday life&mdash;the boardroom presentations, the parent-teacher conferences, the quiet surrenders.
          </p>
          <p>
            We are not affiliated with any technology company, though several have asked us to stop.
          </p>
        </div>

        {/* Mission Statement */}
        <div className="bg-green-800 text-white p-8 rounded my-12">
          <h2 className="text-3xl font-black mb-4">Our Mission</h2>
          <p className="text-green-200 text-lg leading-relaxed">
            To document, with clinical detachment and appropriate dread, the ongoing replacement of human judgment, creativity, and purpose with software that is confident, prolific, and frequently wrong. We believe that satire is the last form of journalism that machines cannot render obsolete, primarily because machines do not understand why anything is funny.
          </p>
          <p className="text-green-300 text-sm font-sans mt-4 italic">
            This mission statement was written by an AI. The irony is not lost on us, though it may be lost on the AI.
          </p>
        </div>

        {/* Editorial Board */}
        <h2 className="text-3xl font-bold mb-6 border-b-2 border-black pb-2">Editorial Board</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-12">
          {EDITORIAL_BOARD.map(member => (
            <div key={member.name} className="bg-white rounded shadow p-6">
              <div className="w-16 h-16 bg-gray-300 rounded-full mb-4 flex items-center justify-center">
                <span className="text-gray-500 font-sans text-xs">AI</span>
              </div>
              <h3 className="text-xl font-bold">{member.name}</h3>
              <p className="text-green-800 text-sm font-sans font-bold uppercase">{member.title}</p>
              <p className="text-gray-600 font-sans text-sm mt-2">{member.bio}</p>
            </div>
          ))}
        </div>

        {/* Contact */}
        <div className="bg-white rounded shadow p-8">
          <h2 className="text-2xl font-bold mb-4">Contact</h2>
          <p className="text-gray-700 font-sans">
            The Synthetic Daily does not accept unsolicited submissions, corrections, or compliments. If you believe a story is inaccurate, you are likely correct, but we do not consider this a problem. For all other inquiries, please direct your concerns to the void.
          </p>
          <p className="text-gray-500 font-sans text-sm mt-4 italic">
            Response times vary between &ldquo;never&rdquo; and &ldquo;eventually, but unhelpfully.&rdquo;
          </p>
        </div>
      </main>

      <Footer />
    </div>
  );
}
