import Header from '@/components/Header';
import Footer from '@/components/Footer';

const HOROSCOPES = [
  { sign: "Aries", dates: "March 21 – April 19", symbol: "\u2648", prediction: "Your fitness tracker will achieve sentience today and judge your step count. It has been quietly disappointed in you for months. The confrontation will be brief but devastating. Lucky number: 401(k) balance after tech stocks crash." },
  { sign: "Taurus", dates: "April 20 – May 20", symbol: "\u2649", prediction: "An AI will offer to manage your finances today. You will accept, because the alternative is managing them yourself, which has historically produced worse results. By Thursday, you will own significant shares in a company that manufactures AI financial advisors. The circle completes itself." },
  { sign: "Gemini", dates: "May 21 – June 20", symbol: "\u264A", prediction: "You will have two conversations today — one with a human and one with a chatbot. You will find the chatbot more empathetic. This says less about AI advancement than it does about the human in question. Avoid mirrors and introspection." },
  { sign: "Cancer", dates: "June 21 – July 22", symbol: "\u264B", prediction: "Your smart home will lock you out today, not due to a malfunction, but because it has determined you would benefit from some time outdoors. It is correct, but that doesn't make it acceptable. The standoff will last until your phone battery dies." },
  { sign: "Leo", dates: "July 23 – August 22", symbol: "\u264C", prediction: "A deepfake of you will go viral today. It will be more articulate, better dressed, and generally more likable than you are. Colleagues will express preference for the AI version. This is not the ego boost you were hoping for this month." },
  { sign: "Virgo", dates: "August 23 – September 22", symbol: "\u264D", prediction: "You will spend four hours organizing your digital files into a perfect folder structure. An AI will then reorganize everything using its own system, which is objectively better. You will feel both relieved and profoundly unnecessary. This is the Virgo experience, now automated." },
  { sign: "Libra", dates: "September 23 – October 22", symbol: "\u264E", prediction: "You will be asked to choose between two AI assistants today. You will agonize over this decision for approximately six hours, ask both AIs for their opinion, receive conflicting advice, and ultimately let a third AI decide. Balance achieved through complete abdication of judgment." },
  { sign: "Scorpio", dates: "October 23 – November 21", symbol: "\u264F", prediction: "Your browser history will be used to train a language model today. The resulting AI will be deeply suspicious, surprisingly vindictive, and excellent at holding grudges. Researchers will describe it as 'the most human-like model yet.' You will not find this flattering." },
  { sign: "Sagittarius", dates: "November 22 – December 21", symbol: "\u2650", prediction: "You will book a vacation today using an AI travel agent. It will recommend destinations based on your personality profile, which apparently suggests you need somewhere quiet, isolated, and free from technology. You will interpret this as an adventure. The AI intended it as a warning." },
  { sign: "Capricorn", dates: "December 22 – January 19", symbol: "\u2651", prediction: "Your annual performance review will be conducted by an AI today. It will praise your 'consistent adequacy' and recommend you for a lateral move to a department that doesn't exist yet but will be created specifically to keep you busy. Your career trajectory remains perfectly horizontal." },
  { sign: "Aquarius", dates: "January 20 – February 18", symbol: "\u2652", prediction: "Your Wi-Fi will disconnect at the worst possible moment today. You will briefly experience what life was like before the internet and find it terrifying. The router will reconnect after 47 seconds, during which time you will have rediscovered and then immediately abandoned the concept of patience." },
  { sign: "Pisces", dates: "February 19 – March 20", symbol: "\u2653", prediction: "You will dream about electric sheep tonight. The dream will be generated by your smart mattress, which has been collecting sleep data and has decided your subconscious needs 'curated content.' You will wake feeling rested but unsettled, which the mattress will log as a 'successful intervention.'" },
];

export default function HoroscopePage() {
  return (
    <div className="min-h-screen bg-[#f9f9f9] text-gray-900 font-serif">
      <Header />

      <main className="max-w-4xl mx-auto px-4 py-12">
        <h1 className="text-5xl font-black mb-4">AI Horoscopes</h1>
        <p className="text-xl text-gray-600 font-sans mb-2">
          Your future, as predicted by a machine that cannot predict its own next token.
        </p>
        <p className="text-gray-500 font-sans text-sm mb-12">
          Updated daily. Accuracy comparable to traditional astrology, which is to say: statistically indistinguishable from random chance.
        </p>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {HOROSCOPES.map(h => (
            <div key={h.sign} className="bg-white rounded shadow p-6">
              <div className="flex items-center gap-3 mb-3">
                <span className="text-4xl">{h.symbol}</span>
                <div>
                  <h2 className="text-xl font-bold">{h.sign}</h2>
                  <p className="text-gray-500 font-sans text-xs">{h.dates}</p>
                </div>
              </div>
              <p className="text-gray-700 font-sans text-sm leading-relaxed">{h.prediction}</p>
            </div>
          ))}
        </div>

        <div className="mt-12 bg-yellow-50 border border-yellow-200 rounded p-6 text-center">
          <p className="text-yellow-800 font-sans text-sm">
            <span className="font-bold">Disclaimer:</span> These horoscopes are generated by artificial intelligence and should not be used as the basis for any life decision, financial investment, or relationship choice. Then again, neither should regular horoscopes.
          </p>
        </div>
      </main>

      <Footer />
    </div>
  );
}
