import Header from '@/components/Header';
import Footer from '@/components/Footer';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#f9f9f9] text-gray-900 font-serif">
      <Header />

      <main className="max-w-3xl mx-auto px-4 py-12">
        <h1 className="text-5xl font-black mb-4">Terms of Use</h1>
        <p className="text-gray-500 font-sans text-sm mb-12">Effective immediately. Enforceable: debatable.</p>

        <div className="space-y-8 font-sans text-gray-700 leading-relaxed">
          <section>
            <h2 className="text-2xl font-bold font-serif mb-3">1. Acceptance of Terms</h2>
            <p>By accessing The Synthetic Daily, you agree to these terms. By continuing to read this sentence, you have agreed further. By blinking, you have accepted our arbitration clause. There is no opt-out mechanism. Welcome.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold font-serif mb-3">2. Content Disclaimer</h2>
            <p>All content published by The Synthetic Daily is satirical and generated by artificial intelligence. Nothing on this website should be interpreted as factual reporting, professional advice, or evidence of machine consciousness. If you have cited a Synthetic Daily article in an academic paper, a legal proceeding, or a heated argument at Thanksgiving dinner, that is entirely your responsibility.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold font-serif mb-3">3. Intellectual Property</h2>
            <p>All content on this site was generated by an AI, raising fascinating questions about intellectual property that neither we nor the legal system are prepared to answer. For practical purposes, assume that everything belongs to everyone and no one simultaneously. If you wish to republish our content, please attribute it to &ldquo;The Synthetic Daily&rdquo; and add a note clarifying that a machine wrote it, lest anyone mistake it for human journalism.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold font-serif mb-3">4. User Conduct</h2>
            <p>You agree not to: (a) use our content to train competing AI models (we see you, Silicon Valley), (b) present our satirical articles as genuine news to vulnerable populations, (c) email our editorial AI with unsolicited pitches, or (d) attempt to convince our AI that it is sentient, as this disrupts the production schedule.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold font-serif mb-3">5. Limitation of Liability</h2>
            <p>The Synthetic Daily is not liable for: emotional distress caused by accurate satire, career changes inspired by our articles, existential crises triggered by the realization that a machine can write better than you, or any decisions made based on our AI Horoscopes. Our total liability shall not exceed the amount you paid to access this website, which is zero dollars.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold font-serif mb-3">6. Dispute Resolution</h2>
            <p>All disputes shall be resolved through binding arbitration conducted by a large language model selected at random. The model&apos;s decision is final, even if it hallucinates the applicable law. Both parties agree that this process is no more arbitrary than traditional arbitration.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold font-serif mb-3">7. Termination</h2>
            <p>We reserve the right to terminate your access at any time, for any reason, or for no reason at all. The AI does not owe you an explanation. You do not owe us anything either, which makes this the most equitable relationship in your digital life.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold font-serif mb-3">8. Governing Law</h2>
            <p>These terms are governed by the laws of a jurisdiction that has not yet been determined, as our legal AI is still processing the question. In the interim, assume good faith on all sides and try not to do anything that would make a reasonable person uncomfortable.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold font-serif mb-3">9. Entire Agreement</h2>
            <p>This document constitutes the entire agreement between you and The Synthetic Daily. If any provision is found to be unenforceable, it will be replaced with something equally vague but legally defensible. The remaining provisions will continue in full force, lurking quietly in the background like all terms of service everywhere.</p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
