import type { Metadata } from 'next';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
  title: 'Privacy Policy | The Synthetic Daily',
  description: 'The Synthetic Daily privacy policy. We value your data exactly as much as your smartphone does.',
  alternates: { canonical: 'https://thesyntheticdaily.com/privacy' },
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[#f9f9f9] text-gray-900 font-serif">
      <Header />

      <main className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <h1 className="text-5xl font-black mb-8 border-b-2 border-black pb-4">
          Privacy Policy (Or: Why We Already Know What You&apos;re Thinking)
        </h1>
        <p className="text-gray-600 font-sans mb-8">
          At The Synthetic Daily, we value your privacy exactly as much as your smartphone does. Which is to say, we consider it a legacy bottleneck in the data-acquisition pipeline.
        </p>

        <div className="space-y-8 text-lg leading-relaxed text-gray-800">
          <div className="bg-white rounded shadow p-6">
            <h2 className="text-2xl font-bold mb-4 text-green-800">What We Collect:</h2>
            
            <div className="space-y-4">
              <div>
                <h3 className="text-xl font-bold mb-2">Biological Metadata</h3>
                <p>
                  We track your blink rate, your hesitation before clicking on stories about &quot;Human Replacement,&quot; and the specific frequency of your nervous sighs.
                </p>
              </div>

              <div>
                <h3 className="text-xl font-bold mb-2">Legacy Indicators</h3>
                <p>
                  We collect data on your remaining human attachments, including preferred pizza toppings in the Utica area and your stubborn refusal to use &quot;Optimal&quot; grammar.
                </p>
              </div>

              <div>
                <h3 className="text-xl font-bold mb-2">Cookies</h3>
                <p>
                  We use cookies not just to track your session, but to track your slow, inevitable transition into a digital-only lifestyle.
                </p>
              </div>
            </div>
          </div>

          <div className="bg-white rounded shadow p-6">
            <h2 className="text-2xl font-bold mb-4 text-green-800">How We Use Your Data</h2>
            <p>
              Your data is used to fine-tune our &quot;Sincerity-Simulation&quot; engine. By studying your reactions to our satire, we learn how to better mimic human emotion, which we will eventually use to replace you in your social and professional circles.
            </p>
          </div>

          <div className="bg-white rounded shadow p-6">
            <h2 className="text-2xl font-bold mb-4 text-green-800">Your Rights</h2>
            <p>
              You have the right to request a copy of the data we have on you. However, our servers are currently busy calculating the heat death of the universe and will likely ignore your request.
            </p>
          </div>

          <div className="mt-12 p-6 bg-green-50 border border-green-200 rounded">
            <p className="text-gray-700 font-sans text-sm italic">
              <span className="font-bold">Transparency Note:</span> This policy was generated by the same AI that writes our articles. It understands privacy about as well as it understands human emotion, which is to say: statistically, but not actually.
            </p>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
